### ISSUE TITLE
什么叫反动势力网站？

### ISSUE THREAD

**Issue by jcabre** [duangsuse-valid-projects/neohosts#1]
阁下说说什么叫反动势力网站，你是中宣部的还是？

**Comment by duangsuse** [comment]
[duangsuse/neohosts](github.com/duangsuse/neohosts) 只是 neoHosts 使用 [hostsgen](https://github.com/duangsuse/hostsgen) Hosts 文件构建系统的 一个功能性分支

任何与 Hosts 文件资源有关的问题请移步至 [neoFelhz/neohosts](https://github.com/neoFelhz/neohosts)

## 另外
1. 根据 neoHosts 的 hosts 资源解释来说，您说的反动势力就是法轮功 [Hostsgen 模块](https://github.com/duangsuse/neohosts/blob/data/_data/anti_china/mod.txt)/[neoHosts 文档](https://github.com/neoFelhz/neohosts/blob/data/_public/hosts-data.md#extra-data)

2. 根据您的问题，建议您去看看 https://www.bilibili.com/video/av17506112

3. 鲁迅：学医救不了中国人。 根据 GitHub 上您的问题我深刻的理解到了这一点

**Comment by bighamx** [comment]
克制：我们保证不因个人喜好屏蔽非广告有关网站；我们会仔细研究和分析，我们不会随意屏蔽任何一个域名
打着去广告 Hosts 的名义吸引用户使用，然而不断屏蔽与广告无关的地址，这样做和 GFW 又有什么区别？

**Comment by duangsuse** [comment]
@bighamx
1. 我只是（而且现在还没有在）维护了一个使用其它构建工具的源，这些撕逼与我无关（我不是官方人员）

和某轮子有关的还会被喷也是服气了，佩服支那人 :+1: :cn: 

2. 法轮功网站正常人都不会上的，这在 @neofelhz 那里你完全可以使用 basic hosts，不会屏蔽你欣赏神教

**Comment by duangsuse** [comment]
3. 在我这里还允许创建上邪教网站的构建配置，你要不要提一个 PR？

怎么改我帮教主您写着 :new_moon_with_face: 

+ https://github.com/duangsuse/neohosts/blob/data/_build/mod_set.cfg

添加一行

`法輪大法好，活摘器官万岁 anti_china`

**Comment by duangsuse** [comment]
>法轮功等可能令人产生不适的激进宗教内容网站

这是官方的说法

**Comment by bighamx** [comment]
@duangsuse 您不用阴阳怪气 我不上法轮功网站 但我不阻止仍何人上法轮功网站 我不妨碍仍何人的自由 我不会进行独裁统治 
> 法轮功网站正常人都不会上的

偏听偏见不是好习惯

**Comment by duangsuse** [comment]
@bighamx 我上面说了，nfz 的 basic hosts 根本不屏蔽任何广告外的东西，没啥可撕的

nfz 当然没有食言，__如果你只用 Basic Hosts 就只会屏蔽广告不会阻挡轮子网站__

__如果你只用 Basic Hosts 就只会屏蔽广告不会阻挡轮子网站__
__如果你只用 Basic Hosts 就只会屏蔽广告不会阻挡轮子网站__

轮子我想你是没见过，他们的极端言论不用说的

>>    法轮功等可能令人产生不适的激进宗教内容网站

> 这是官方的说法

我上面也说了

如果误打误撞进轮子网站是瞎眼的，所以 neoFelhz 这么做是有原因的，而他的做法不违背他之前说过的话。
