### ISSUE TITLE
下载405

### ISSUE THREAD

**Issue by jiangying000** [duangsuse-valid-projects/neohosts#2]
* 有关此 `issue` 的目的：(请将 `[ ]` 中的空格替换为 `x` 以勾选)
- [ ] 反馈误杀/申请解封（影响到关键服务的正常运行)
- [ ] 申请审查（申请维护者对一个含广告的网站进行分析和数据完善)
- [ ] 提交域名/数据（发现一个广告域名，想提交给 neoHosts)
- [x] 申请技术支持
- [ ] 其它问题

---

* 您要反馈的问题：
无法打开下载链接https://neko-dev.github.io/neohosts/basic/hosts

**Comment by duangsuse** [comment]
@djy0 很抱歉呢，本项目本来是 neoHosts 的分支，数据上没有任何区别
现在已经暂停维护
你可以去上游 [neoFelhz/neoHosts](https://github.com/neoFelhz/neohosts) 开相同的 issue
